### ISSUE TITLE
GitHub Actions workflow to validate pull requests

### ISSUE THREAD

**Issue by jeff-matthews** [AdobeDocs/dev-site-documentation-template#79]
### Expected Behaviour

An event-driven GitHub Actions workflow that validates pull requests to the `main` branch to ensure contributions don't get merged with the production branch and break the production build.

### Actual Behaviour

There is no automated validation for pull requests to the `main` branch. A contribution could break the build, but you might not know until _after_ merging with `main` and attempting to deploy. Requiring a reviewer to check out a branch and run a build locally is unreliable. We should use automation to catch breaking changes before they get into the production branch.

### Reproduce Scenario (including but not limited to)

Delete a required file or add invalid syntax to a required file.

#### Steps to Reproduce

n/a

#### Platform and Version

n/a

#### Sample Code that illustrates the problem

Here's a simple workflow that builds the Gatsby project for pull requests to the `main` branch:

```
# Validate pull requests to the main branch

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build site
        run: npm run build
```

#### Logs taken while reproducing problem

n/a
